name: Publish Docker image
on:
  push:
    branches:
      - "master"
      - "main"
    paths:
      - ".github/workflows/*"
      - "scripts/*"
      - "dockerfiles/*.Dockerfile"
  #release:
  #  types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create .env
        run: echo "GITHUB_PAT=${GITHUB_TOKEN}" >> ".env"
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: dockerfiles/ja_latest.Dockerfile
          tags: |
            docker.pkg.github.com/${{ github.repository }}/ja:${{ github.sha }}
            docker.pkg.github.com/${{ github.repository }}/ja:latest
          secret-files: |
            "dotenv=.env"
