name: Publish Docker image
on:
  push:
    branches:
      - "master"
      - "main"
    paths:
      - "scripts/*"
      - "dockerfiles/*.Dockerfile"
  #release:
  #  types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create env file
        run: echo "GITHUB_PAT=$GITHUB_TOKEN" >> ".env"
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: dockerfiles/ja_latest.Dockerfile
          tags: "docker.pkg.github.com/atusy/atusy-rocker/ja:latest"
          build-arg:
            - "--secret id=dotenv,src=.env"
